
version: '3.3'

services:
  redis:
    image: redis:5.0
    ports:
      - 6379:6379

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.0.0
    ports:
      - 9200:9200
      - 9300:9300
  
  rabbitmq:
    image: rabbitmq:3.7.0
    ports:
      - 4369:4369
      - 5671:5671
      - 5672:5672
      - 25672:25672

  mysql:
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - 3306:3306

  tests:
    depends_on:
      - redis
      - mysql
      - rabbitmq
      - elasticsearch
    network_mode: host
    build: .
    volumes:
        - ./:/book
    command: sh
